chat-format:
  default: "&7{PLAYER} &8» &f{MESSAGE}"
  VIP: "&6[VIP] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  grywacz: "&2[SVIP] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  SPONSOR: "&1[SPONSOR] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  elita: "&d[ELITA] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  Bogacz: "&6&l[BOGACZ] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  admin: "&c[Admin] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  owner: "&4[Właściciel] &8ₓ &7{PLAYER} &8» &6{MESSAGE}"

messages:
  automsg:
    - "&8&m»                       «\n
       &8● &aCashMiner.pl &8●\n
       &7Czy wiesz, ze istnieje komenda &e/sklep\n
       &7Możesz tam sprzedać i kupić np. klucze!\n
       &8&m»                       «"
    - "&8&m»                       «\n
       &8● &aCashMiner.pl &8●\n
       &7Zobacz najbogatszych graczy na serwerze!\n
       &7Wpisz &e/topki\n
       &8&m»                       «"
    - "&8&m»                       «\n
       &8● &aCashMiner.pl &8●\n
       &7Możesz odebrać swoją nagrodę na serwerze!\n
       &7Użyj komendy &e/discord &7aby dowiedzieć się więcej!\n
       &8&m»                       «"
    - "&8&m»                       «\n
       &8● &aCashMiner.pl &8●\n
       &7Znalazłeś cheatera?\n
       &7Zgłoś to administracji na discordzie lub pod komendą &e/helpop!\n
       &8&m»                       «"
    - "&8&m»                       «\n
       &8● &aCashMiner.pl &8●\n
       &7Aktualna granica mapy wynosi &e2000x2000 kratek\n
       &8&m»                       «"
    - "&8&m»                       «\n
      &8● &aCashMiner.pl &8●\n
      &7Top 3 graczy, którzy wykopali najwięcej bloków na koniec edycji otrzymują nagrody:\n
      &7TOP 1 - &ebrush 6x6\n
      &7TOP 2 - &ebrush 5x5\n
      &7TOP 3 - &ebrush 4x4\n
      &6Wpisz &e/topki\n
      &8&m»                       «"
    - "&8&m»                       «\n
      &8● &aCashMiner.pl &8●\n
      &7Chcesz kopać szybciej i więcej? Zajrzyj na naszą stronę internetową &ehttps://cashminer.pl\n
      &8&m»                       «"

shopSell:
  '1':
    title: "64x cobbla"
    cost: 0.01
    type: COBBLESTONE
    items: "COBBLESTONE 64"
    commands: []
  '2':
    title: "64x redstone"
    cost: 0.50
    type: REDSTONE
    items: "REDSTONE 64"
    commands: []
  '3':
    title: "64x lazuryt"
    cost: 1
    type: "LAPIS_ORE"
    items: "LAPIS_ORE 64"
    commands: []
  '4':
    title: "4x diamenty"
    cost: 2
    type: "DIAMOND"
    items: "DIAMOND 4"
    commands: []
  '5':
    title: "2x szmaragdy"
    cost: 2
    type: "EMERALD"
    items: "EMERALD 2"
    commands: []
  '6':
    title: "64x żelazo"
    cost: 0.25
    type: "IRON_INGOT"
    items: "IRON_INGOT 64"
    commands: []
  '7':
    title: "64x złota"
    cost: 0.25
    type: "GOLD_INGOT"
    items: "GOLD_INGOT 64"
    commands: []
  '8':
    title: "64x ziemii"
    cost: 0.02
    type: "DIRT"
    items: "DIRT 64"
    commands: []
  '9':
    title: "4x obsydianu"
    cost: 1
    type: "OBSIDIAN"
    items: "OBSIDIAN 4"
    commands: []
  '10':
    title: "8x deski"
    cost: 0.05
    type: "WOOD"
    items: "WOOD 8"
    commands: []
# todo: klucze

shopBuy:
  '1':
    title: "64x cobbla"
    cost: 0.02
    type: COBBLESTONE
    items: "COBBLESTONE 64"
    commands: []
  '2':
    title: "64x redstone"
    cost: 1
    type: REDSTONE
    items: "REDSTONE 64"
    commands: []
  '3':
    title: "64x lazuryt"
    cost: 2
    type: "LAPIS_ORE"
    items: "LAPIS_ORE 64"
    commands: []
  '4':
    title: "4x diamenty"
    cost: 4
    type: "DIAMOND"
    items: "DIAMOND 4"
    commands: []
  '5':
    title: "2x szmaragdy"
    cost: 4
    type: "EMERALD"
    items: "EMERALD 2"
    commands: []
  '6':
    title: "64x żelazo"
    cost: 0.5
    type: "IRON_INGOT"
    items: "IRON_INGOT 64"
    commands: []
  '7':
    title: "64x złota"
    cost: 0.5
    type: "GOLD_INGOT"
    items: "GOLD_INGOT 64"
    commands: []
  '8':
    title: "64x ziemii"
    cost: 0.04
    type: "DIRT"
    items: "DIRT 64"
    commands: []
  '9':
    title: "4x obsydianu"
    cost: 2
    type: "OBSIDIAN"
    items: "OBSIDIAN 4"
    commands: []
  '10':
    title: "8x deski"
    cost: 0.10
    type: "WOOD"
    items: "WOOD 8"
    commands: []