chat-format:
  default: "&7{PLAYER} &8» &f{MESSAGE}"
  VIP: "&6[VIP] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  SVIP: "&2[SVIP] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  SPONSOR: "&1[SPONSOR] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  elita: "&d[ELITA] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  Bogacz: "&6&l[BOGACZ] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  admin: "&c[Admin] &8ₓ &7{PLAYER} &8» &f{MESSAGE}"
  root: "&4[Właściciel] &8ₓ &7{PLAYER} &8» &6{MESSAGE}"

messages:
  automsg:
    - "&8&m»                       «\n
       &8● &aInformacja &8●\n
       &7Na tym serwerze istnieje komenda &e/sklep\n
       &7Wejdź i coś kup, albo sprzedaj :O"
    - "&8&m»                       «\n
       &8● &aInformacja &8●\n
       &7Chcesz zobaczyć najlepszych graczy na serwerze?\n
       &7Sprawdź to w komendzie &e/topki"
    - "&8&m»                       «\n
       &8● &aInformacja &8●\n
       &7Nie zapomnij odebrać nagrody na serwerze!\n
       &7Użyj komendy &e/discord &7aby dowiedzieć się więcej!"
    - "&8&m»                       «\n
       &8● &aInformacja &8●\n
       &7Widzisz cheatera?\n
       &7Zgłoś to administracji przez komendę &e/helpop!"
    - "&8&m»                       «\n
       &8● &aInformacja &8●\n
       &7Aktualna granica mapy wynosi &e2200x2200 kratek"

shopSell:
  '1':
    title: "DIAMENT"
    cost: 3.2
    type: DIAMOND
    items: DIAMOND
    commands: "say elo jestem kurwom"
  '2':
    title: "ZŁOTO"
    cost: 5.5
    type: GOLD_INGOT
    items: GOLD_INGOT
    commands: "say elo jestem kurwom"

shopBuy:
  '1':
    title: "DIAMENT"
    cost: 3.2
    type: DIAMOND
    items: DIAMOND
    commands: "say elo jestem kurwom"
  '2':
    title: "ZŁOTO"
    cost: 5.5
    type: GOLD_INGOT
    items: GOLD_INGOT
    commands: "say elo jestem kurwom"